hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_ntopo/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - output_dir_disp
          - output_dir_density
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 2023
log_freq: 500
output_dir: ${hydra:run.dir}
output_dir_disp: ${hydra:run.dir}/disp
output_dir_density: ${hydra:run.dir}/density

# set problem parameters
PROBLEM: "Beam2D"

# set working condition
NU: 0.3
E: 1.0
VOLUME_RATIO: 0.5
SIGMOID_ALPHA: 5.0
ENERGY_EXP: 3.0  # TODO: trainable parameter
PENALTY: 10
MAX_MOVE: 0.2
DAMPING: 0.5  # 阻尼参数

USE_MMSE: true
USE_OC: true
FILTER: "Gaussian"  # "sensitivity"
FILTER_SIGMA: 1.0

input_keys_2d: ["x_scaled", "y_scaled",  "sin_x_scaled", "sin_y_scaled"]
input_keys_3d: ["x_scaled", "y_scaled", "z_scaled", "sin_x_scaled", "sin_y_scaled", "sin_z_scaled"]
output_keys_2d: ["u", "v"]
output_keys_3d: ["u", "v", "w"]
# model settings
MODEL:
  disp_net:
    input_keys: ${input_keys_2d}
    output_keys: ${output_keys_2d}
    num_layers: 6
    hidden_size: 180
    last_layer_init_scale: 1.0e-3
  density_net:
    input_keys: ${input_keys_2d}
    output_keys: ["density",]
    num_layers: 6
    hidden_size: 180
    last_layer_init_scale: 1.0e-3

# training settings
TRAIN:
  epochs: 100  # times for for-loop
  disp_net:
    epochs: 1
    iters_per_epoch: 1000
    optimizer:
      learning_rate: 3.0e-4
      beta2: 0.99
      epsilon: 1e-7
  density_net:
    epochs: 1
    iters_per_epoch: 50
    optimizer:
      learning_rate: 3.0e-4
      beta1: 0.8
      beta2: 0.9
      epsilon: 1e-7
  save_freq: 10
  eval_during_train: false
  eval_freq: 100
  pretrained_model_path: null
  checkpoint_path: null
  enable_parallel: false # whether to enable parallel training

# evaluation settings
EVAL:
  num_sample: 10000
  pretrained_model_path: null
  n_cells: [100, 50, 25]
